## YAML Template.
---
categories:
    annotation: Genome Annotation
    assembly: Genome Assembly
    communities: Microbial Communities
    comparative_genomics: Comparative Genomics
    expression: Expression
    metabolic_modeling: Metabolic Modeling
    reads: Read Processing
    sequence: Sequence Analysis
    util: Utilities
orderings:
    default: analysis
    analysis:
        - reads
        - assembly
        - annotation
        - sequence
        - comparative_genomics
        - metabolic_modeling
        - expression
        - communities
        - utilities
